[package]
name = "hpyhex_rspy"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "hpyhex_rspy"
crate-type = ["cdylib"]

[dependencies]
hpyhex-rs = "0.1.0"
libc = "0.2.180"
